{
 "title": "机场监控",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "当前余额",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "Limit": 20, "expr": "current_balance" }
   ]
  },
  {
   "title": "当前最大带宽上线 (MB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "Limit": 20, "expr": "max_bandwidth" }
   ]
  },
  {
   "title": "同时在线设备数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "Limit": 20, "expr": "online_device_count", "legendFormat": "device" }
   ]
  },
  {
   "title": "距离下一个账单日",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "Limit": 20, "expr": "remain_time" }
   ]
  },
  {
   "title": "今日已使用流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    { "Limit": 20, "expr": "today_used", "legendFormat": "Used" }
   ]
  },
  {
   "title": "剩余可用流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    { "Limit": 20, "expr": "remain_flow", "legendFormat": "RemainFlow" }
   ]
  }
 ]
}